// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyStore.Models;

namespace MyStore.Migrations
{
    [DbContext(typeof(produitsContext))]
    [Migration("20200323212806_CreationInitial")]
    partial class CreationInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("prducts.Models.Produits", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.Property<string>("Descprod")
                        .IsRequired()
                        .HasColumnName("descprod")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<decimal?>("Discprod")
                        .HasColumnName("discprod")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<byte[]>("Improd")
                        .IsRequired()
                        .HasColumnName("improd")
                        .HasColumnType("image");

                    b.Property<string>("Namprod")
                        .IsRequired()
                        .HasColumnName("namprod")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal>("Priprod")
                        .HasColumnName("priprod")
                        .HasColumnType("numeric(18, 0)");

                    b.HasKey("Id");

                    b.ToTable("produits");
                });
#pragma warning restore 612, 618
        }
    }
}
